### ISSUE TITLE
Can not knit RTEAnalytics-Sergey-01.Rmd 

### ISSUE THREAD

**Issue by Sefimenko** [brrav0/RTEAnalytics#16]
Dear Theos, 
I tried to find the solution in stackoverflow but I failed to find/understand/implement/ 
Could you please help us with the following:

I would like to knit RTEAnalytics-Sergey-01.Rmd including  this chunks:

``` r echo=TRUE, eval=TRUE, comment=NA, warning=FALSE, message=FALSE, results='asis’
m1<-gvisTable(regression_data,options=list(showRowNumber=TRUE,width=1920, height=min(400,27*(nrow(regression_data)+1)),allowHTML=TRUE,page='disable'))
print(m1,'chart')
```

and 

``` r echo=TRUE, eval=TRUE, comment=NA, warning=FALSE, message=FALSE, results='asis’
library(corrplot)
corrplot(cor(regression_data[1:25]), method = "color", type="upper", order="original", tl.col="black", tl.srt=70)
```

...but I constantly get such errors as:

processing file: RTEAnalytics-Sergey-01.Rmd
(*) NOTE: I saw chunk options "echo=TRUE, eval=TRUE, comment=NA, warning=FALSE, message=FALSE, results='asis<U+2019>"
 please go to http://yihui.name/knitr/options
 (it is likely that you forgot to quote "character" options)
Error in base::parse(text = code, srcfile = NULL) : 
  1:80: unexpected INCOMPLETE_STRING
1: alist( echo=TRUE, eval=TRUE, comment=NA, warning=FALSE, message=FALSE, results='asis<U+2019> )
                                                                                   ^
Calls: <Anonymous> ... withCallingHandlers -> eval -> parse_only -> <Anonymous>
Execution halted

...  I also got errors that were specific to corrplot and gvisTable functions

Thanks,
Sergey

**Comment by tevgeniou** [comment]
i see no problem when knit the file after making only these changes - so it also runs the lines needed:

``` r echo=TRUE, eval=TRUE, comment=NA, warning=FALSE,error=FALSE, message=FALSE, prompt=FALSE, tidy=TRUE, results='asis'
m1<-gvisTable(regression_data,options=list(showRowNumber=TRUE,width=1920, height=min(400,27*(nrow(regression_data)+1)),allowHTML=TRUE,page='disable'))
print(m1,'chart')

```

``` r, echo=FALSE
library(corrplot)
corrplot(cor(regression_data[1:25]), method = "color", type="upper", order="original", tl.col="black", tl.srt=70)
```

in the note above there is a quote missing after "asis". should be results='asis'  (it also says "(it is likely that you forgot to quote "character" options)"). 

also, better not to use the table for the whole (large) matrix `regression_data`. it is too big to be loaded on html 

> dim(regression_data)
> [1] 52608    28

show only, say, the first 100 or 1000 rows or so. 
m1<-gvisTable(regression_data[1:100,],options=list(showRowNumber=TRUE,width=1920,
